---
title: Testing
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
minimal_mistakes_skin: contrast
locale: en
title_separator: "-"
name: test
description: test
url: https://iqbaladinur.github.io
baseurl: "/"
repository: 
teaser: 
breadcrumbs: true
words_per_minute: 200
comments:
  provider: disqus
  disqus:
    shortname: brianrakhmataji
  discourse:
    server: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 
staticman:
  allowedFields:
  - name
  - email
  - url
  - message
  branch: master
  commitMessage: New comment.
  filename: comment-{@timestamp}
  format: yml
  moderation: true
  path: docs/_data/comments/{options.slug}
  requiredFields:
  - name
  - email
  - message
  transforms:
    email: md5
  generatedFields:
    date:
      type: date
      options:
        format: iso8601
atom_feed:
  path: 
google_site_verification: _6RN4s00-wWvFccB1puckaG0DYetJ2cN96MoOtOXX0Q
bing_site_verification: 7E7F617410E2CC9EDD131AE0513C04EB
alexa_site_verification: 
yandex_site_verification: 
twitter:
  username: brianrakhmat
facebook:
  username: 
  app_id: 
  publisher: 
og_image: 
social:
  type: 
  name: 
  links: 
analytics:
  provider: google
  google:
    tracking_id: UA-91050478-3
author:
  name: Brian Rakhmat Aji
  avatar: "/assets/images/bio.png"
  bio: A Student Informatics Engineering
  location: Yogyakarta, Indonesia
  email: brianetlab@gmail.com
  uri: 
  bitbucket: 
  codepen: 
  dribbble: 
  flickr: 
  facebook: Brian Rakhmat Aji
  foursquare: 
  github: brianrakhmat
  gitlab: 
  google_plus: 
  keybase: 
  instagram: brianrakhmat
  lastfm: 
  linkedin: brianrakhmat
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: 
  tumblr: 
  twitter: brianrakhmat
  vine: 
  weibo: 
  xing: 
  youtube: 
include:
- ".htaccess"
- _pages
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- vendor
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- Rakefile
- README
- tmp
- "/docs"
- "/test"
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/page:num/"
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jekyll-admin
- jemoji
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  ignore:
    envs: development
