title: Stuck Stories
description: Personal Stuck Stories 
author: Iqbal Adi Nurmansyah
github: https://github.com/iqbaladinur
about: Freelance developer. Currently focus on web development.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/iqbaladinn1"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/iqbaladinur"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/iqbaladinur"

share:
  twitter_username: agusmakmun6
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://iqbaladinur.github.io/blog"
baseurl: "https://iqbaladinur.github.io/blog"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
